### PR TITLE
Fixed navigating into folders in branches. Fix #541

### LINKED ISSUE #541: Repository Browser: viewing a branch other than 'master'
I can use the repository browser just fine when going through the folders (and files) of a repository when the 'master' branch is selected, however, when selecting a different branch, the directory is reset back to the root folder of the repo. When selecting a subfolder again, the repo browser switches back to the 'master' branch and then displays the subfolder. Simply said: i cannot view any subfolder (or file) of a branch different than 'master'. 

Using Bonobo Git Server (5.2.0.0)
Tested with: Chrome 49.0.2623.110

### PR DESCRIPTION
**Pull request by RedX2501**
@willdean  Will you have a look and commit if you please?

### CODE REVIEW

**Comment by RedX2501** [comment]
@willdean Do you think it is mergeable now?

**Comment by larshg** [comment]
I just tried it out and it seems to be working. However if I navigate to a  file and then want to change branch (or select the same to get to root) it returns Item not found.

I tried to debug it, but in the sort time I had on my hand, I couldn't locate the error.

**Comment by RedX2501** [comment]
@larshg I think i fixed it. Please check it out.

**Comment by larshg** [comment]
Yes you did :) 

But I just noticed that when I'm on  branch and click the home button, then it returns to master branch? and not just home of current branch :D

**Comment by RedX2501** [comment]
@larshg Ok I hope I fixed that properly too now.

**Comment by larshg** [comment]
Yes, its working - I think its great to merge it :+1:

**Pull request merged**
