### PR TITLE
Win auth fixes

### PR DESCRIPTION
**Pull request by willdean**
Fix the Windows Auth with EF Membership scenario - see #668 

@larshg - could you have a very quick look - it does seem that your ADHelper does all the heavy lifting and there was nothing much left to do in GitAuthAttr, which is great if it's true.

@brianhv Would you mind trying this one when it's built, please?

### CODE REVIEW

**Comment by larshg** [comment]
All logging is also in this one :-) ?

**Comment by willdean** [comment]
Yes, but they're two branches, and once I merge the logging one separately this one will look more sensible...

**Comment by larshg** [comment]
Ah, for what I can validate from my phone, it seems fine :-)

**Comment by larshg** [comment]
Ah, for what I can validate from my phone, it seems fine :-)

**Comment by brianhv** [comment]
Tested. Works for me!

**Comment by larshg** [comment]
@willdean can you "release" the 6.1? or should we do some more logging in AD sync etc for better support in this area?

**Comment by willdean** [comment]
@larshg I did it last week - I think maybe I forgot to tag this repo, though, so I'll do that now.  It's up at https://bonobogitserver.com/

**Comment by larshg** [comment]
ahh, I just lookhed [here](https://github.com/jakubgarfield/Bonobo-Git-Server/releases) :)

**Comment by willdean** [comment]
Yes, thanks for the reminder!  You can look again now...

**Pull request merged**
