### PR TITLE
Use default domain as it might be different from mail domain.

### LINKED ISSUE #602: AD Install loses repo settings in upgrade from 5.2 to 6.0 pre-release
In #587 @Trapulo posted 

> @willdean tried to update to last build. Lost every repo details (users permissions, logos, and other details) but all seems ok. Tried a little sync and commit from Visual Studio and all seems ok. Is there some specific trouble may I search?

@Trapulo, assuming you have a backup copy of your old 5.2 install, could you see if you have an "ADBackend" directory in app_data for both 5.2 and 6.0 installs, and if you can see any obvious difference between the files in the "Repos" subdirectory in both installs.

I don't think it should have lost all your repo settings on that upgrade.

### PR DESCRIPTION
**Pull request by larshg**
Alternatively implement to test both. Might fix #602

### CODE REVIEW

**Comment by willdean** [comment]
I am really weak on this stuff, and can't tell what other problems this creates - I like the option you mentioned in #602 of trying for the domain in the email address and falling back to the default if that doesn't work - that feels safer than just using the default-domain.  I have a feeling that the whole business of pulling domains out of email addresses started because there were people who couldn't just use the default domain.

**Comment by larshg** [comment]
Ahh okay - I'll eventually try to make the required changes then.

**Comment by larshg** [comment]
@willdean I have made the required changes. @RedX2501 can you have a look too?

**Comment by willdean** [comment]
Looks good to me - I can't test this here, but I think the approach looks OK.

**Comment by willdean** [comment]
@larshg Are you happy this works OK on your setup for importing users that have both the default domain and a different domain?  If so then I think we should merge it and then push for a 6.0-beta release.  @RedX2501  is busy on other things at the moment and I don't think he can easily test AD stuff anyway.

**Comment by larshg** [comment]
Well, yes and no... It seems to work, but if one extracts the domain from the UPN (email) name and its different from the domain controller, it takes a long time to timeout and try the default domain... But I can't really come up with a better solution - at least for now - so lets go ahead and merge, to get some feedback?

**Comment by larshg** [comment]
I have just read more about AD, domains and UPN suffixes... For what I understand, the UPN suffixes is rarely the same as the domain name of the AD server and hence I don't think we should extract the suffix from logon name etc.

Either we should use the default domain from settings - or we should create a principal context with no domain specified and it will try to connect whatever the webserver domain is part of?

One explanation of additional suffixes can be read [here](http://www.tutorialspoint.com/articles/adding-alternate-upn-suffix-to-active-directory-domain).

Naming of AD servers FQDN is dicussed [here](http://serverfault.com/questions/76715/windows-active-directory-naming-best-practices)  - ie. ad1.domain.com.

I don't think that if we extract domain.com from a logon name that the AD server would respond on this - because it should be on a subdomain...

**Comment by larshg** [comment]
I guess the original problem was reported by #562 from @mr-miles.

**Comment by willdean** [comment]
@larshg If we shouldn't be pulling domain names out of user names at all, does that mean that routines like `GitAuthorizeAttribute.IsWindowsUserAuthorized` are mistaken?

That uses a helper called `StripDomain` (it's mis-named, it should really be called `ExtractDomain`) to get a domain out of user@domain and then builds a PrincipalContext from that. 

I too am concerned about long delays in the import, that something in IIS will then interrupt the import and cause all sorts of impossible to debug problems with partial imports.

Maybe we should just try to make things work properly using the 'Default Domain' for a 6.0-beta, and then look careful at situations where this doesn't work properly for people?   (I'm sorry as I know that's where you started with this PR)

**Comment by larshg** [comment]
Well, that is what I get out of all the reading :) - also, when I create the PrincalContext with the adress of our domain server my user is validated using the full UPN name - whereas the current `StripDomain` does remove the suffix of the UPN ie. @domain.com - but this shouldn't be necessary.

An alternative to the multi domain/server problem could be to change the DefaultDomain to a list of AD servers, which is then iterated. As long as the server is connected, the verification of a valid user is quite fast, so it shouldn't take long to validate a couple of servers? But again... if there are servers not up and running, it can take a long time to timeout the servers that are not available. Both on upgrade, but also when verifying all the git operations etc.

I'm still trying to read up on how to handle trusted domains from one domain to another in a multi domain/forest setup :)

**Comment by willdean** [comment]
The project so needs an AD expert - it's great that you've selected yourself  :-) 👍

**Comment by larshg** [comment]
A Microsoft [article](https://msdn.microsoft.com/en-us/library/ff650307.aspx) that describes what I suggested about multiple servers :)

**Comment by willdean** [comment]
@larshg Doesn't that article describe exactly what we have been doing, which is obtaining a domain name by splitting it out of a UPN?

**Comment by larshg** [comment]
Unfortunately yes - it does... :/

**Comment by larshg** [comment]
[This](https://www.codeproject.com/Articles/18102/Howto-Almost-Everything-In-Active-Directory-via-C) article might be good read. I can see that we can access the forest and get first the root domain and any subdomain / servers and iterate all, until a user is found etc.

I'll try read up on it during the week.. Lets wait a bit with merging!

**Pull request closed without merging**
