### PR TITLE
Fix for issue #407

### PR DESCRIPTION
**Pull request by chrismdev**
Replace first occurrence of character

### CODE REVIEW

**Comment by kfarnung** [comment]
I would recommend changing "UserNameHelper" to be "StringExtensions" following the pattern here:

https://msdn.microsoft.com/en-us/library/bb383977.aspx

That will allow the code to look like:

username.ReplaceFirstOccurrence("!", @"\");

**Comment by kfarnung** [comment]
Another question, what's special about the first occurrence?  I'm not familiar with the domain of the problem, but is there anything else distinct about the "first occurrence" that could make the replacement even more scoped?

**Comment by chrismdev** [comment]
Hi, this is my first PR so I appreciate the feedback.

I don't have a reason for choosing a static instead of an extension method. You're right, it would be neater but I wasn't sure I should be polluting the string class with my own newbie methods.

The problem is that when using windows authentication the "\" causes problems in the UI and has been replaced with an "!".

My code was just to replace the "!" with a "\ "so that windows auth would work again.

**Comment by kfarnung** [comment]
You should probably make the class static as well, it has no instance members.

The reason I was suggesting making it part of StringExtensions was that the method, as coded, has no username functionality.  If you internalized the characters to replace, then I think "UserNameHelpers" makes more sense, but in the current form it just seems like "StringHelpers."

The extension methods are nice because they only pollute the class when you have the namespace enabled and they are essentially just static methods, but the IDE/compiler helps them be contextual rather than hidden off in a class somewhere.

**Comment by chrismdev** [comment]
Good point, will rewrite as an extension method.

**Pull request closed without merging**
