### PR TITLE
[RTM] Make all tests dispose Repos, Teams and Users automatically

### PR DESCRIPTION
**Pull request by RedX2501**
This creates Disposable for Repositories, Teams and Users, which should delete themselves after each test.

### CODE REVIEW

**Comment by RedX2501** [comment]
Please merge this as fast as you can. I need this to make the other two PRs finally work properly.

**Comment by willdean** [comment]
GH reckons this will merge OK - is there a problem with doing that?

**Comment by willdean** [comment]
I'm not going to make a big deal of this, but I actually don't think this basic premise of this PR is a good idea.  I think the solution to the test-interaction problem is good setup, not more complex clean-up after tests run.

My problem with this approach is:
* It makes the tests more complex (you need to remember the using, and there's more indent, etc)
* It makes the tests run more slowly, because the cleanup takes time
* A mistake in one test (forgetting a using) may cause a failure not in that test but in a different one.

But it's better than manual deletion of stuff, which is what we had before...

**Comment by RedX2501** [comment]
I agree that this is not fast. The using is actually totally optional. At the end of the test stuff should be destroyed.

Doing the merge should be fine. I rebased it making sure that it shoud be a clean fast forward.

Please merge whenever you feel like it.

**Comment by RedX2501** [comment]
Im not even sure why I'm using an IDisposable interface. I could make them delete at the destructor.

I saw that you already have a branch with the other option. I guess I'll just wait for that.

**Pull request closed without merging**
