### PR TITLE
Fix for ADRoleProvider

### LINKED ISSUE #459: AD authentication not working for Administrator access
Hello All,

I'm having an issue getting an administrative login via Active Directory.  I am able to successfully login using AD, just not as an administrative user.

Unexpected behavior:
- When attempting to login as an administrative user I can login, but receive the error "Unauthorized
You don't have permission for the selected action or page."

Troubleshooting:
- The machine is connected to AD.  I can successfully login with an AD user as a regular user.
- Nested groups are not being used.
- Case sensitivity is not the issue - I've tried case correct and lower case.
- Local admin will not work when AD authentication is used.  This is to be expected I suppose, but limits workarounds.

Here is the user authentication block from the web.config file:
```
  <add key="UserConfiguration" value="~\App_Data\config.xml" />
    <add key="DefaultRepositoriesDirectory" value="~\App_Data\Repositories" />
    <add key="GitPath" value="~\App_Data\Git\git.exe" />
    <add key="GitHomePath" value="~\App_Data" />
    <add key="RecoveryDataPath" value="~\App_Data\Recovery" />
    <add key="AuthenticationProvider" value="Cookies" />
    <!--<add key="AuthenticationProvider" value="Windows" />-->
    <!--<add key="AuthenticationProvider" value="Federation" />-->

    <!--<add key="MembershipService" value="Internal" />-->

    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="ulaneocu.org" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="Git1101Gitall" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=Git1101Admin" />
    <!--<add key="ActiveDirectoryTeamMapping" value="Developers=GitTeam" />-->

```
Thanks in advance for your assistance and time,
Sean

### PR DESCRIPTION
**Pull request by chrismdev**
Hopefully this fixes #459

### CODE REVIEW

**Comment by willdean** [comment]
This is clearly a fix for a bug, but sadly I doubt it's a fix for  #459 problem, because the bug you're fixing is a regression on the Guid ID work, which wasn't in the version which is being run in #459

**Comment by chrismdev** [comment]
Fair enough. It does fix the same issue in master though.

**Comment by willdean** [comment]
ok, cool, TVM.   I've merged it, though I will probably make a minor stylistic tweak in that the rest of the project compares GUIDs with == rather than .Equals.    

I think really RoleProvider has far to much username stuff going on in it - it should all be guids now, but anyway...

**Comment by xiaoyuvax** [comment]
i still meet problem #459 with the officially downloaded binary,when there will be a update?

**Comment by willdean** [comment]
@xiaoyuvax I don't think there's a problem as general as "administrator role doesn't work for AD" - it's more likely something about your particular setup which Bonobo doesn't work well with, and hopefully you'll be able to help us work out what it is.

Could you please have a look in the app_data\logs directory for the latest log, and see if you can see in there anything which gives a clue what might be happening - feel free to attached it here if you want me to have a look.

**Comment by xiaoyuvax** [comment]
@willdean 
the log attached for you analysis (i guess that a few chinese characters won't frustrate you ;-):

[log-20170624.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/1099710/log-20170624.txt)

**Comment by willdean** [comment]
Thanks for that - would you mind looking in web.config and changing this line:

```
<add key="serilog:minimum-level" value="Information" />
```
 to say 

```
<add key="serilog:minimum-level" value="Verbose" />
```

Then try again and give us the logs again.   For some reason I'm not quite sure about it's losing the domain name somewhere.

**Comment by xiaoyuvax** [comment]
[log-20170624_new.txt](https://github.com/jakubgarfield/Bonobo-Git-Server/files/1099845/log-20170624_new.txt)

note that server fs. is down.

**Comment by willdean** [comment]
@xiaoyuvax - thanks for the logs - can we move to #706 please

**Pull request merged**
