### PR TITLE
Allow repo to be saved by server-admin without a repo admin being set

### LINKED ISSUE #501: Git Admins shouldn't need to mark their own accounts as repo administrators when editing permissions
Right now, when a server-wide admin opens the Edit dialog for a repository, they have to tag their account as an administrator within the administrator list for that repo in order to be able to save changes. Not doing so throws the error "You can't remove yourself as an administrator".

This seems a bit counter-intuitive, as it shouldn't matter whether or not a server admin is an admin over a specific repository - they're going to have access regardless.

### PR DESCRIPTION
**Pull request by willdean**
Fixes #501 

I tried to write some integration tests, but got stuck at trying to get SpecsForMvc to find all the admin checkboxes and turn them off.

### CODE REVIEW

**Comment by RedX2501** [comment]
I created a PR on your repo with checkboxselection example.

**Comment by RedX2501** [comment]
I noticed that we have not being updated the changelog file properly. Do you mind adding an entry for this PR?

**Comment by willdean** [comment]
@RedX2501 This branch is currently failing test on AppVeyor in RepoAdminCannotRemoveThemselves at the point where it tries to create a user. This works when I run the test on its own locally.

I suspect this might be because the user already exists as a hang-over from an earlier test - does each test method in the xxxControllerTests get a clean start, or could they be interacting? I notice lots of tests are doing 'DeleteRepository' at the end, which they shouldn't need to do if the framework is cleaning up.

**Comment by RedX2501** [comment]
As far as I understand the framework it will copy the contents of the bin folder only once when starting. I also think that it starts the server only once. This means that whatever is left in the DB after each test is still there.

To circumvent problems with left behind repois i have made the CreateRepos function now return an IDisposable. This should probably be done for the CreateUser function too.

**Comment by willdean** [comment]
Better post-test cleanup is good, but it might also not be unreasonable to have some kind of local-only 'reset database' call into Bonobo, which could be used by the test framework to initialise the database into a known state before each test.

We could then perhaps have both an 'empty' (admin only, no repos) condition, and a 'test mode' condition, which pre-loaded a configuration with a repos and a couple of non-admin users, and perhaps a team.   If we had a standardised test setup, then it would save having to write that stuff into individual tests, and it would be much faster to run each test if the framework didn't need to painfully step through endless web-pages setting it up.

Do you think we could come up with a standardised setup which would be a helpful starting point for writing tests?

**Pull request merged**
