### PR TITLE
Attempt at a fix for #475

### PR DESCRIPTION
**Pull request by chrismdev**
Attempt at a fix for #475. Apologies for my coding style.

### CODE REVIEW

**Comment by RedX2501** [comment]
I don't think that is the right approach as the User.Id should NEVER be empty if you are authorized.

My guess is that due to the background service in AD that fills in the users it has not been added yet.

@larshg Maybe we need to revert https://github.com/jakubgarfield/Bonobo-Git-Server/commit/2af315756ebec6bfcf05f43b09d3fd073c186186?

**Comment by chrismdev** [comment]
But aren't we talking about 2 different contexts? The browser context and the git context. Yes the User.Id should never be null from a browser but git does not have access to that cookie/session. Git has to re-authenticate somehow.

**Comment by RedX2501** [comment]
Git does a full http authentication (cookie or windows auth) before it reaches the GetSecureInfoRefs part.

Set a breakpoint at the authentication code and you will see it.

**Comment by larshg** [comment]
@chrismdev you can try debug through the OnAuthorization in GitAuthorizeAttribute - this should authenticate you when using a git client.

And the git client should prompt for username and password if you use the general url - also if you use credential store you might have to clear it, if you have old values saved etc.

**Comment by RedX2501** [comment]
@larshg the problem is that we never get to see the passwords unless internal auth is used. IIRC This means the pipeline will auth the user against the AD and let it proceed. The next step will then try to fetch this user again and becaus it has not been added to the backend by the background worker it will still have an GUID of 0.

**Comment by larshg** [comment]
@RedX2501  what do mean that we never get to see the passwords? Your git client has to be authenticated somehow by providing a username and password?

**Comment by RedX2501** [comment]
You are right on the git side. I was thinking about the Browser side when using Windows Auth.

**Comment by larshg** [comment]
So if you run your site as a intranet and you should automatically be authenticated, bonobo is not presented with username and password?

Because I still have to supply user and password (atleast first time when running chrome) - microsoft edge browser ask for it each time its started - but maybe the url of the remote and local bonobo server I have, is not correctly added as a trusted site :)

**Comment by RedX2501** [comment]
Yes, the first time you set username and password (or not if internet explorer does the ntlm handshake) and then a cookie is set on your system. Based on that cookie the user is then retrieved from the DB.

**Comment by chrismdev** [comment]
Have created a new pull request for this

**Pull request closed without merging**
