### PR TITLE
Compatibility with IE version.

### PR DESCRIPTION
**Pull request by holiiveira**
I was having compatibility issues with more current versions of IE, this configuration solved my problem.

### CODE REVIEW

**Comment by RedX2501** [comment]
What kind of problems were you having?

**Comment by holiiveira** [comment]
No problem about the operation, only problem with layout (buttons that do not appear), maybe some incompatibility of javascript, I do not know for sure.

**Comment by willdean** [comment]
I normally just add this into the head of the layout page rather than adding more stuff to web.config.  I do think we should have it though, as without it some versions of IE lag a long way behind current browsers.

**Comment by holiiveira** [comment]
I understand, your solution is cool.

**Pull request closed without merging**
