### PR TITLE
Feature: Commit messages like in github

### PR DESCRIPTION
**Pull request by alexkuznetsov**
Hello!

I refactor commit messages, now they look like in github.
I have the trouble with storing splitted commit messages, i use for it properties Message and MessageShort. 
Any ideas for refactor, suggestions?

Screenshots:
Default state:
screenshot_1
Expanded state:
screenshot_2

### CODE REVIEW

**Comment by jakubgarfield** [comment]
Thanks for the PR, I need to review it more closely and hopefully will manage to do it by the end of the week.

**Comment by alexkuznetsov** [comment]
@jakubgarfield thank you for response. As i say, there are some tricks in my solution. 
I am open for any recommendation for refactor.

**Comment by jakubgarfield** [comment]
Nice work, personally I'd be happy with just using string.Substring instead of breaking based on the words size.

And having a decorator instead of helper + model would be also my preferred choice. Something like

```
CommitMessageDecorator
   ctor(message);
   prop String Title;
   prop String Details;
```

but your implementation is working and the feature is really nice :)

**Comment by alexkuznetsov** [comment]
@jakubgarfield, thank you for the merging!

I will try to implement the approach with decorator. 
The solution with breaking based on words size for me is more good instead using of subscring - all words are **comleate** in that case.

**Comment by whosa** [comment]
I found XSS in this pull request. If you write javascript in commit message , it will be run.

**Pull request merged**
