### PR TITLE
Don't allow unknown AD users to be admins before ADCreateUser

### PR DESCRIPTION
**Pull request by willdean**
Potential fix for #687

### CODE REVIEW

**Comment by willdean** [comment]
@larshg It's [this line](https://github.com/jakubgarfield/Bonobo-Git-Server/pull/691/commits/bdec7efff9e79efda863b37e9bf17cd72ff12576#diff-05c1790487572d68236e1424d03dd7c2R208) which I think should make the current user into an admin.

**Comment by larshg** [comment]
I'll try it out tomorrow :-) but it looks Loke it should work!

**Comment by willdean** [comment]
@larshg Thanks!  What timezone are you in?  (I am in the UK, so UTC+1 in the summer)

**Comment by larshg** [comment]
For some odd reason, the added claim is not present after the redirect. Somehow it is not properly written to the cookie? The ClaimsIdentity is created with string litteral(SignInAsAuthenticationType) specifying "Cookies". 
I guess thats how we avoid having to reauthenticate against the AD all the time?

**Comment by willdean** [comment]
We might need to sign in again after adding the claim?  Have a look at this;

http://stackoverflow.com/questions/20383955/how-to-add-claims-in-asp-net-identity

Perhaps if we do the 'signin' bit again after adding the claim?

**Comment by willdean** [comment]
Or the accepted answer on [here](http://stackoverflow.com/questions/24587414/how-to-update-a-claim-in-asp-net-identity) might be useful?

**Comment by larshg** [comment]
Yes, the last suggestion works.

I have made some changes, but for some reason github is rejecting my pushes atm.

**Comment by larshg** [comment]
On a site note... Isn't it a security risk saving rights in Cookie - then as a long as this cookie lives, the user can have admin roles etc. I tried for the fun of it to promote a second user to admin, but I had to relog and clear cookies for it to get the new roles from the DB.

Also the other way around, when I removed the admin rights of the first account, it first disappeared after logging out and clearing the cookies.

I know its a short period of time and properly a rare case... but sometimes you could have a crazy colleague :D

**Comment by larshg** [comment]
Uhh and I'm in DK, so its the same, UTC +1 :)

**Comment by willdean** [comment]
>I have made some changes, but for some reason github is rejecting my pushes atm
Are you trying to push to my branch - that's probably the problem - I'll give you access, hang-on...

**Comment by willdean** [comment]
@larshg You should have had a collaboration invite for my fork from GH?

**Comment by larshg** [comment]
@willdean - I was trying to push to my own repository :-) 
But I'm busy this weekend, but maybe I get a spare minute to try to push again :-)

**Pull request merged**
