### PR TITLE
Updated to msysGit-1.9.5-preview20150319

### PR DESCRIPTION
**Pull request by larshg**
I did the following to test it:

Created a new repository
Cloned it
Added a new file and commited and pushed it.

All went well - you mentioned some errors in #189 - how can I provoke these?

### CODE REVIEW

**Comment by jakubgarfield** [comment]
I think that last time I did this simple test, it failed.

Try to run the regression test as described https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server.Test/MsysgitIntegrationTests.cs

**Comment by larshg** [comment]
I just tried to debug it a little and this are the changes i noticed:

CloneEmptyRepository:
Originally output is: Cloning into Integration...   - new output is "" ie empty string.
Originally error: warning: You appear to have cloned an empty repository. - new output is: Cloning into 'Integration'...
warning: You appear to have cloned an empty repository.

So it seems that they have moved all the output to the error output.

The output is also changed for the following subtests:
CloneRepository
PullRepository
Pulltag

How would you go about it? Want to make a if/switch depending on the git version and correct the "expected" output? or take it to msysgit git page and ask for clarification?

It seems that git 1.9.5-preview20150319 does what it supposed to, it "just" print out differently, ie. more/less data in either output or error stream.

**Comment by jakubgarfield** [comment]
If/switch would be fine for this type of testing - there will be only one version of git on the server though.

**Comment by larshg** [comment]
@jakubgarfield I have updated the test so 1.9.5 passes.
I changed it to use relative paths from debug/release folder.
I have only tested 1.8.1.2, 1.8.3 and 1.9.5.

**Comment by jakubgarfield** [comment]
Awesome, nice work! :)

**Comment by latop2604** [comment]
In the csproj, some git dll are referenced but not exits in the repo.
I do not found any error after removing broken reference. But I can miss something.

**Comment by larshg** [comment]
@latop2604 I just recloned the repository and I didn't get any missing references - maybe the nuget restore didn't complete properly?

**Comment by latop2604** [comment]
image

**Pull request merged**
