### PR TITLE
Closed value tag.

### PR DESCRIPTION
**Pull request by YopparaiNeko**
Tried building latest commit and VS found this unclosed tag.

### CODE REVIEW

**Comment by YopparaiNeko** [comment]
I'm new at contributing here, why the closing?

**Comment by jakubgarfield** [comment]
Damn, cause I clicked on a wrong button. Sorry @YopparaiNeko :)

**Comment by mattn** [comment]
@YopparaiNeko Thanks. Good catch.

**Comment by YopparaiNeko** [comment]
No problem, glad I could assist. :D

**Pull request merged**
