### PR TITLE
Add Controller Tests, fix #659 (1ef6921) and other features listed below

### LINKED ISSUE #659: Repository URL does not work
Hi, I installed clear installation on W2012R2 IIS server (http://intranet/), creation of repository is without problem, the url on the repository http://intranet/Bonobo.Git.Server/Repository/intranet works correctly, but any attempt to go to url "General url" : "http://intranet/Bonobo.Git.Server/intranet.git" shows error 404 and in the IIS log there is row
2017-03-29 16:23:39 192.168.10.136 GET /Bonobo.Git.Server/intranet.git - 80 Jan+Němec 192.168.8.48 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/56.0.2924.87+Safari/537.36 http://intranet/Bonobo.Git.Server/Repository/intranet 200 0 0 0

I have no clue where to search another log error

### PR DESCRIPTION
**Pull request by eugeniomiro**
This PR adds the following features

* 110 Controller tests added (2 skipped).
  * These test methods are testing the current behavior of Controllers in particular, so they we can start refactoring with a Safety Net
  * There are two Ignored tests in the list, that mark two refactoring points to create new infrastructure code to avoid direct DbContext dependencies
  * Not all controllers are fully tested yet, but I'm in the process of creating all required tests for that
* Solves #659
  I installed a server and used it with my team for our internal development projects and found that, when using Remote button in Sourcetree, the repository was not found. This PR includes a fix for that, together with tests covering the new code
* Updates Unity package to 5.11.7
* Moves all Unit tests to the Unit namespace
* Refactors ConfigurationEntry for testability
* Adds .editorconfig file
* Unity configuration code was moved into App_Start/UnityConfig class
* Test framework was migrated to MSTestV2

### CODE REVIEW

**Comment by willdean** [comment]
@eugeniomiro Thanks very much for all this work, it's very much appreciated.

However I'm sorry to say that there no way anyone can possibly review all these changes in a single PR.  

I would be happy to merge a big PR which was purely improvements to the testing, but there's no way that I could merge so many unrelated things which affected the project so much.

If you have fixed an existing bugs, then it would be much better to file a single PR which just fixed that bug.
If you have found a new bug then it would be better to file a bug AND a PR which fixes just that bug.

I feel really bad when someone has put in so much work, but I can't merge this as it is, sorry.

**Comment by eugeniomiro** [comment]
Hi @willdean, Sorry about the big PR, I understand what you're saying, but the fact is that, much of the code is testing code, and it's new code, not changing any existing one. There are just some changes to the existing code other than renaming test namespaces.
I'm sorry you can't accept these changes, however I will continue creating more of these for me, because I'm using the software as I sent it to you guys and it is very effective for me. 
I will try to create a new PR in the future, only with tests for you to have most of the tests I have.

**Comment by willdean** [comment]
Thanks - That would be great - if you want to make a new branch (or branches) based at the current head, and then cherry-pick your existing test commits across into that branch, that will make a cleaner PR.

**Comment by eugeniomiro** [comment]
Yeah, will do that, but I started with a little change to the code, so I need to figure out what to include in those cherry picks, you'll see my new PR soon. Thanks for all.

**Pull request closed without merging**
