### PR TITLE
Mixed Authentication: Current Local Form Authentication and Custom Asp.net Form Authentication

### PR DESCRIPTION
**Pull request by selcukermaya**

### CODE REVIEW

**Comment by jakubgarfield** [comment]
Hi, there are multiple changes in the commit so I don't understand what the focus of the change is. Also, commented code is not acceptable. What is the benefit of introducing forms authentication and how does it cope with git authentication?

**Comment by selcukermaya** [comment]
Hi, Last commit is OK. 

Custom Form Authentication for custom membership providers. When Git ask username and password it's validating from custom membership provider.

And I didn't understand "commented code is not acceptable." ^^ What do you mean?

If you don't want to publish it I OK with that ^^

**Comment by jakubgarfield** [comment]
If you switch to the FormsAuthentication on the project, does git client still works? As it needs to use the basic authentication to communicate with IIS.

What's the benefit of using FormsAuthentication here? To be able to use different Forms membership providers? I don't understand what we are getting with this commit (but that's due to my lack of knowledge, so I need an explanation :)

By not accepting a commented code I meant FormsIdentityImporter.cs that contains it with the combination of badly named variables (windowsIdentity variable is certainly not a part of FormsIdentity).

Also, empty general catch statements are not a good practice https://github.com/selcukermaya/Bonobo-Git-Server/blob/717aa2ccb6cc6f3d72e1768cd765ffd8357b15a0/Bonobo.Git.Server/Security/EFMembershipService.cs#L39

But mostly I'm struggling with understanding what this PR brings to the project.

**Comment by selcukermaya** [comment]
Ahh Sorry. 

The benefits of using FormAuthentication is use different Forms Membership Providers ofc ;)

Let me tell you something about my story.

I am using different authentication works with Custom Forms Authentication Provider. Its connecting to our company users database to check username and password. With this provider we are using single database for our all web applications.

When I saw your Bonobo I really love it because its so easy to use and add more futures. One of  them is my custom provider. I changed a couple of places to allow this usage ;)

I am so sorry about my poor english ^^ If you want to ask specific questions I will able to answer nicely ^^ 

Once again thank you so much for this project!

**Comment by mikehaas763** [comment]
@selcukermaya I can see forms authentication working from the web interface, but does it work from git clients? Forms authentication uses cookies to track the user and I'm not sure that will work with git clients such as visual studio or any of the other ones.

**Comment by selcukermaya** [comment]
I'm using it with tortoise git client.


*Selçuk Ermaya*
Just a Developer
http://www.selcukermaya.com
*[M] *+90 533 523 32 45

**Comment by jakubgarfield** [comment]
I'm sorry but I have to reject the pull request for now. It modifies several unrelated files and it's hard for me to see and test the change. However, I'll keep it on my mind if there is a need for FormsAuthentication in the future. Despite that, I really appreciate the time and the effort you put in the commit -- thank you.

**Pull request closed without merging**
