### PR TITLE
Fix issue #254

### PR DESCRIPTION
**Pull request by padremortius**

### CODE REVIEW

**Comment by jakubgarfield** [comment]
Does the raw view still fail? Do you have an idea why?

**Comment by padremortius** [comment]
> Does the raw view still fail?
No.
>Do you have an idea why?
No.

**Comment by jakubgarfield** [comment]
It doesn't? wow, I don't understand :)

**Comment by padremortius** [comment]
Very strange work highlign.js. In manual written that class="nohighlight" - turn off highlight... But not... Hightlight is still work. May be update this component?

**Pull request merged**
