### PR TITLE
Implement External System Links Functionality and Tags List #383

### PR DESCRIPTION
**Pull request by kabongsteve**
I have implemented two features
A Regex and Links URL combo to allow extraction of linkage information from Commit messages and allow links to external systems.

We use FogBugz for Issue Tracking and enter the Case# into the Commit message.  This allows links from Bonobo into the FogBugz Cases.
Maybe help with Issue #306. 

Secondly, I refactored the TagName into a Tags list and show each separately to correct Issue #383

Steve

### CODE REVIEW

**Comment by jakubgarfield** [comment]
Hi, I'm currently away from computer - I'll have a look at your PR when I'm back after New Year. Thanks for understanding :)

**Comment by jotatoledo** [comment]
Hi there @jakubgarfield , @kabongsteve 

Could I get some help to configurate the 2 options on settings for my commits to have the following functionalities:

- Have a link to the commit on my BonoboGitServer
- Have a link to an issue inside of an issue tracker system

For example:

If I make the following commit:

```
Fixed(Global.asax.cs): corrected IoC container configuration

Corrected the configuration of the unity IoC. Fixes #5891
```

I would like to parse it into:

```
Fixed(Global.asax.cs): corrected IoC container configuration

Corrected the configuration of the unity IoC. Fixes [#5891](https://some-issue-tracking-system.com/project_name/issues/5891)
```

Is this possible? Any help would be appreciated!

**Comment by willdean** [comment]
@jotatoledo Could you please create a new issue if you need help, rather than adding onto the end of an old PR - thanks.

**Comment by jotatoledo** [comment]
Ofc!

**Pull request merged**
