### PR TITLE
Increase button column width to prevent line break caused by long button texts.

### PR DESCRIPTION
**Pull request by mischalandwehr**
line-break

### CODE REVIEW

**Comment by jakubgarfield** [comment]
How about reducing the length of the Neues Repository erstellen? That would prevent breaking to two lines with the benefit of keeping valuable space for repository titles.

**Comment by mischalandwehr** [comment]
IMHO the German resources are improvable. "Neues Repository erstellen" could shorten to "Repository erstellen" (you always create new things), "Repository Verwaltung" to "Repositories", ... Some translations are missing or faulty. So putting some love to the German resources could solve this breaking, too.

But a fix via shorting the title is only a fix for the current desktop version. If we want to extend it for tablets and smartphones we will get the same problem again. The "royal way" would be to increase the column width and than updating the German resources.

**Comment by jakubgarfield** [comment]
On tablets and smartphones it should (in theory) just stack under each other as it is using the responsive grid, right? Maybe each button should have it's own column (1-5).

**Comment by mischalandwehr** [comment]
If you place each button in 1-5 columns, the gap between them will be very large. The current small gap  nicer. 

To enable tablets you could change the classes to "pure-u-1 pure-u-md-x-5". This would break the buttons under the headline and all would look great.

**Comment by jakubgarfield** [comment]
Which solution would you prefer? I'm happy to merge your current PR or wait for the responsive one.

**Comment by mischalandwehr** [comment]
I would prefere to merge this PR.

Next week I will fix the German translations and after that the responsive one.

**Pull request merged**
