### PR TITLE
Added support for grouping repositories.

### PR DESCRIPTION
**Pull request by LennardF1989**
As requested per issue #134 

NOTE: This does not affect the file-system (yet).

### CODE REVIEW

**Comment by jakubgarfield** [comment]
Thanks for the PR - I made a few comments, have a look and after few small modifications I'll be happy to merge.

**Comment by LennardF1989** [comment]
Do you want me to overwrite the branch or just push a second commit with the changes?

**Comment by jakubgarfield** [comment]
Another commit is fine - but merge master as there is one small change that disables automatic merge.

**Comment by LennardF1989** [comment]
Just to be clear, you mean I commit and push my change directly into master on my side, which would prevent an additional merge on yours?

**Comment by LennardF1989** [comment]
I figured out what you meant, didn't notice the updates on your master. Its 5:30AM over here, should probably call it a day, hehe :P

**Comment by jakubgarfield** [comment]
Looking good, thank you :)

**Pull request merged**
